# Command delay
delay:
  enabled: true
  # time in s
  time: 3

spawn-on-spawn: true
spawn-on-respawn: true

# Choose a storage system (mysql or yaml)
storage-system: yaml

mysql:
  host: "localhost"
  port: 3306
  database: vitalspawn
  username: "vitalspawn"
  password: ""
  prefix: "server_"